name: Android CI
on:
    pull_request:
        branches:
            - main
        types: [opened, reopened, synchronize]
    workflow_dispatch:    

jobs:
    code-quality:
        runs-on: ubuntu-latest
        name: Run lint and unit tests

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup JDK environment
              uses: actions/setup-java@v4
              with:
                  distribution: "zulu"
                  java-version: 17

            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@v4

            - name: Run ktlint
              run: ./gradlew lintKotlin

            - name: Run detekt
              run: ./gradlew detekt

            - name: Run tests
              run: ./gradlew test    
              
            - name: Generate coverage report
              run: ./gradlew jacocoCoreDebugCodeCoverage

            - name: Add coverage to PR
              id: jacoco
              uses: madrapps/jacoco-report@v1.7.1
              with:
                  paths: |
                      ${{ github.workspace }}/**/build/reports/jacoco/jacocoCoreDebugCodeCoverage/jacocoCoreDebugCodeCoverage.xml
                  token: ${{ secrets.GITHUB_TOKEN }}
                  min-coverage-overall: 40
                  min-coverage-changed-files: 60
                  title: Code Coverage
                  update-comment: true
                  debug-mode: true   
    build:
      runs-on: ubuntu-latest
      name: build app
      needs: code-quality
      steps: 
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup JDK environment
              uses: actions/setup-java@v4
              with:
                  distribution: "zulu"
                  java-version: 17

            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@v4    
              
            - name: build app  
              run: ./gradlew assembleDebug
