name: Android CI
on:
    pull_request:
        branches:
            - main
        types: [opened, reopened, synchronize]

jobs:
    code-quality:
        runs-on: ubuntu-latest
        name: Run lint and unit tests
        permissions:
            pull-requests: write        

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup JDK environment
              uses: actions/setup-java@v4
              with:
                  distribution: "zulu"
                  java-version: 17

            - name: Cache Gradle
              uses: actions/cache@v3
              with:
                path: | 
                        ~/.gradle/caches
                        ~/.gradle/wrapper  
                key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
                restore-keys: |
                      ${{ runner.os }}-gradle-      

            - name: Run ktlint
              run: ./gradlew lintKotlin

            - name: Run detekt
              run: ./gradlew detekt
              
            - name: Generate coverage report
              run: ./gradlew jacocoCoreDebugCodeCoverage

            - name: Add coverage to PR
              id: jacoco
              uses: madrapps/jacoco-report@v1.7.1
              with:
                  paths: |
                      ${{ github.workspace }}/**/jacocoCoreDebugCodeCoverage.xml
                  token: ${{ secrets.GITHUB_TOKEN }}
                  min-coverage-overall: 40
                  min-coverage-changed-files: 60
                  title: Code Coverage
                  update-comment: true
                  debug-mode: true   
    build:
      runs-on: ubuntu-latest
      name: build app
      needs: code-quality
      steps: 
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup JDK environment
              uses: actions/setup-java@v4
              with:
                  distribution: "zulu"
                  java-version: 17

            - name: Cache Gradle
              uses: actions/cache@v3
              with:
                path: | 
                        ~/.gradle/caches
                        ~/.gradle/wrapper  
                key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
                restore-keys: |
                      ${{ runner.os }}-gradle-   
              
            - name: build app  
              run: ./gradlew assembleDebug
              
            - name: Upload Debug Apk
              uses: actions/upload-artifact@v4
              if: success()
              with:
                  name: latest-apk
                  path: "app/build/outputs/apk/core/debug/app-core-debug.apk"          
